
POST http://localhost:8080/
Content-Type: application/json

{
    "name": "testing jwt"
}



###
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "account": "tet3",
    "name": "Le duc huy",
    "email": "myemail@gmail.com",
    "password": "caccac",
    "avatar": "avt"
}
####


POST http://localhost:8080/user/register
Content-Type: application/json

{
    "account": "testaccount3",
    "name": "Le duc huy",
    "email": "myemail@gmail.com",
    "password": "caccac",
    
}
####

POST http://localhost:8080/POST     HTTP/1.1
Authorization: :bearer asfakflafa;lfma;fla

