
GET http://localhost:8080/
Content-Type: application/json

{
    "id": "60bddbe0957ed9172883b790"
}



###
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "account": "taikhoan1",
    "password": "matkhautest1"
}



####
GET http://localhost:8080/user/ldhuy0102work
Authorization: :bearer eyJhbGciOiJIUzI1NiJ9.NjBiZGRiZTA5NTdlZDkxNzI4ODNiNzkw.xlEqFIRb1PdlGO6DtmjNTmD4QtLn_vu8D7jx6AZ7uHQ
Content-Type: application/json


####
POST http://localhost:8080/user/register
Content-Type: application/json

{
    "account": "ldhuy0102work",
    "email": "testemail1@gmail.com",
    "name": "Duc huy",
    "password": "matkhautest1"
}
####

POST http://localhost:8080/post/create HTTP/1.1   
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGQxYTk1M2M0ZGY5ZDBlNzRmYjljMGQiLCJpYXQiOjE2MjQzNTMxMTV9.WRBZddXKqSP1sXLkcAnKZr64lRi3hjW4PvPzCxLajTg
Content-Type: application/json

{
    "content": "Hôm nawy trời đéo đẹp"
}



####
DELETE http://localhost:8080/post/delete/60d006b7d63d2b1fdcd9c350 HTTP/1.1 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGQxYTZkNjQ2NzEyNDFjYTAzMDlkNTAiLCJpYXQiOjE2MjQzNTI0OTN9.U-wkMl0USLTXpnOCxA2DmhUokubnQWC-FePHJzMnTX8


####
POST http://localhost:8080/user/logout HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGNlYjk4ZDIyZDA2NDM4ZWMwYzQxNzYiLCJpYXQiOjE2MjQyOTA0NjR9.QjOzME5bu45BiCfxKyFOzvzrmcdXZuxVh-s4kgHbrNQ